import type { CatalogItem, ProviderDefinition } from './types'

export const CATALOG: CatalogItem[] = [
  {
    key: 'compute',
    title: '计算',
    subtitle: 'Compute',
    description: '提供弹性计算能力，支撑批处理、微服务和长驻应用的核心算力。',
    highlights: ['弹性伸缩与自动调度', '多种实例规格与镜像', '支持与监控、伸缩服务集成'],
    products: {
      aws: 'Amazon EC2',
      gcp: 'Compute Engine',
      azure: 'Virtual Machines',
      aliyun: '弹性计算 ECS',
    },
    iac: {
      aws: {
        detailSlug: 'ec2',
        terraform: 'terraform-aws-modules/ec2-instance/aws',
        pulumi: 'aws.ec2.Instance',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'ec2' },
      },
      gcp: {
        detailSlug: 'compute-engine',
        terraform: 'terraform-google-modules/vm/google',
        pulumi: 'gcp.compute.Instance',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'compute-engine' },
      },
      azure: {
        detailSlug: 'virtual-machines',
        terraform: 'Azure/avm-res-compute-virtualmachine/azurerm',
        pulumi: 'azure-native.compute.VirtualMachine',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'virtual-machines' },
      },
      aliyun: {
        detailSlug: 'ecs',
        terraform: 'aliyun/alicloud//modules/ecs-instance',
        pulumi: 'alicloud.ecs.Instance',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'ecs' },
      },
    },
  },
  {
    key: 'network',
    title: '网络',
    subtitle: 'Networking',
    description: '构建隔离的虚拟网络、子网与路由策略，连接多区域资源。',
    highlights: ['支持多 AZ 网络拓扑', '内外网访问控制策略', '集成流量监控与日志分析'],
    products: {
      aws: 'Amazon VPC',
      gcp: 'Virtual Private Cloud',
      azure: 'Virtual Network',
      aliyun: '专有网络 VPC',
    },
    iac: {
      aws: {
        detailSlug: 'vpc',
        terraform: 'terraform-aws-modules/vpc/aws',
        pulumi: 'aws.ec2.Vpc',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'vpc' },
      },
      gcp: {
        detailSlug: 'vpc',
        terraform: 'terraform-google-modules/network/google',
        pulumi: 'gcp.compute.Network',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'vpc' },
      },
      azure: {
        detailSlug: 'virtual-network',
        terraform: 'Azure/avm-res-network-virtualnetwork/azurerm',
        pulumi: 'azure-native.network.VirtualNetwork',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'virtual-network' },
      },
      aliyun: {
        detailSlug: 'vpc',
        terraform: 'aliyun/alicloud//modules/vpc',
        pulumi: 'alicloud.vpc.Network',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'vpc' },
      },
    },
  },
  {
    key: 'dns_cdn',
    title: 'DNS / CDN',
    subtitle: 'DNS & CDN',
    description: '提供高可用域名解析与全球内容分发，加速访问并保障业务连续性。',
    highlights: ['智能流量调度与健康检查', '边缘缓存与 HTTPS 加速', '与 WAF / DDoS 防护协同'],
    products: {
      aws: 'Amazon Route 53 & CloudFront',
      gcp: 'Cloud DNS & Cloud CDN',
      azure: 'Azure DNS & Front Door',
      aliyun: '云解析 DNS & 全站加速',
    },
    iac: {
      aws: {
        detailSlug: 'route53-cloudfront',
        terraform: 'terraform-aws-modules/cloudfront/aws',
        pulumi: 'aws.cloudfront.Distribution',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'dns-cdn' },
      },
      gcp: {
        detailSlug: 'cloud-dns-cdn',
        terraform: 'terraform-google-modules/cloud-dns/google',
        pulumi: 'gcp.dns.ManagedZone',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'dns-cdn' },
      },
      azure: {
        detailSlug: 'azure-dns-front-door',
        terraform: 'Azure/avm-res-network-dnszone/azurerm',
        pulumi: 'azure-native.network.DnsZone',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'dns-cdn' },
      },
      aliyun: {
        detailSlug: 'dns-acceleration',
        terraform: 'aliyun/alicloud//modules/dns',
        pulumi: 'alicloud.dns.DomainRecord',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'dns-cdn' },
      },
    },
  },
  {
    key: 'security',
    title: '安全防护',
    subtitle: 'Security',
    description: '强化云上网络边界与访问控制，保障业务安全合规运行。',
    highlights: ['细粒度入出站策略控制', '统一日志审计与告警', '可复用的安全基线模板'],
    products: {
      aws: 'VPC Security Group',
      gcp: 'VPC Firewall Rules',
      azure: 'Network Security Group',
      aliyun: '安全组',
    },
    iac: {
      aws: {
        detailSlug: 'security-group',
        terraform: 'terraform-aws-modules/security-group/aws',
        pulumi: 'aws.ec2.SecurityGroup',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'security-group' },
      },
      gcp: {
        detailSlug: 'vpc-firewall',
        terraform: 'terraform-google-modules/network/google//modules/fabric-firewall-rules',
        pulumi: 'gcp.compute.Firewall',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'vpc-firewall' },
      },
      azure: {
        detailSlug: 'network-security-group',
        terraform: 'Azure/avm-res-network-networksecuritygroup/azurerm',
        pulumi: 'azure-native.network.NetworkSecurityGroup',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'network-security-group' },
      },
      aliyun: {
        detailSlug: 'security-group',
        terraform: 'aliyun/alicloud//modules/security-group',
        pulumi: 'alicloud.ecs.SecurityGroup',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'security-group' },
      },
    },
  },
  {
    key: 'load_balancer',
    title: '负载均衡',
    subtitle: 'Load Balancing',
    description: '在多个计算节点间智能分发流量，确保高可用与弹性扩缩。',
    highlights: ['支持七层与四层协议', '内置健康检查与会话保持', '可与自动伸缩策略联动'],
    products: {
      aws: 'Application Load Balancer',
      gcp: 'Cloud Load Balancing',
      azure: 'Azure Load Balancer',
      aliyun: '共享型 SLB',
    },
    iac: {
      aws: {
        detailSlug: 'alb',
        terraform: 'terraform-aws-modules/alb/aws',
        pulumi: 'aws.elasticloadbalancingv2.LoadBalancer',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'alb' },
      },
      gcp: {
        detailSlug: 'cloud-load-balancing',
        terraform: 'GoogleCloudPlatform/lb-http/google',
        pulumi: 'gcp.compute.ForwardingRule',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'cloud-load-balancing' },
      },
      azure: {
        detailSlug: 'azure-load-balancer',
        terraform: 'Azure/avm-res-network-loadbalancer/azurerm',
        pulumi: 'azure-native.network.LoadBalancer',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'azure-load-balancer' },
      },
      aliyun: {
        detailSlug: 'slb',
        terraform: 'aliyun/alicloud//modules/slb',
        pulumi: 'alicloud.slb.LoadBalancer',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'slb' },
      },
    },
  },
  {
    key: 'storage',
    title: '存储',
    subtitle: 'Storage',
    description: '面向非结构化数据的对象存储，提供高耐久与低成本的数据湖基础。',
    highlights: ['多区域冗余存储级别', '事件通知与生命周期管理', '统一访问控制与加密'],
    products: {
      aws: 'Amazon S3',
      gcp: 'Cloud Storage',
      azure: 'Azure Blob Storage',
      aliyun: '对象存储 OSS',
    },
    iac: {
      aws: {
        detailSlug: 's3',
        terraform: 'terraform-aws-modules/s3-bucket/aws',
        pulumi: 'aws.s3.Bucket',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 's3' },
      },
      gcp: {
        detailSlug: 'cloud-storage',
        terraform: 'terraform-google-modules/cloud-storage/google',
        pulumi: 'gcp.storage.Bucket',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'cloud-storage' },
      },
      azure: {
        detailSlug: 'blob-storage',
        terraform: 'Azure/avm-res-storage-storageaccount/azurerm',
        pulumi: 'azure-native.storage.StorageAccount',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'storage-account' },
      },
      aliyun: {
        detailSlug: 'oss',
        terraform: 'aliyun/alicloud//modules/oss',
        pulumi: 'alicloud.oss.Bucket',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'oss' },
      },
    },
  },
  {
    key: 'database',
    title: '数据库',
    subtitle: 'Database',
    description: '托管关系型数据库服务，提供高可用、备份与性能监控能力。',
    highlights: ['自动备份与多可用区部署', '参数模板与性能洞察', '支持主从与只读实例'],
    products: {
      aws: 'Amazon RDS',
      gcp: 'Cloud SQL',
      azure: 'Azure Database for PostgreSQL',
      aliyun: '云数据库 RDS',
    },
    iac: {
      aws: {
        detailSlug: 'rds',
        terraform: 'terraform-aws-modules/rds/aws',
        pulumi: 'aws.rds.Instance',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'rds' },
      },
      gcp: {
        detailSlug: 'cloud-sql',
        terraform: 'terraform-google-modules/sql-db/google',
        pulumi: 'gcp.sql.DatabaseInstance',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'cloud-sql' },
      },
      azure: {
        detailSlug: 'azure-database',
        terraform: 'Azure/avm-res-database-postgresqlflexibleserver/azurerm',
        pulumi: 'azure-native.dbforpostgresql.Server',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'azure-database' },
      },
      aliyun: {
        detailSlug: 'apsaradb-rds',
        terraform: 'aliyun/alicloud//modules/rds-instance',
        pulumi: 'alicloud.rds.Instance',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'apsaradb-rds' },
      },
    },
  },
  {
    key: 'cache',
    title: '缓存',
    subtitle: 'Cache',
    description: '低延迟内存数据库服务，加速会话、排行榜等热点数据场景。',
    highlights: ['兼容 Redis/Memcached 协议', '高可用主从复制', '支持自动故障转移与备份'],
    products: {
      aws: 'Amazon ElastiCache',
      gcp: 'MemoryStore for Redis',
      azure: 'Azure Cache for Redis',
      aliyun: '云数据库 Redis',
    },
    iac: {
      aws: {
        detailSlug: 'elasticache',
        terraform: 'terraform-aws-modules/elasticache/aws',
        pulumi: 'aws.elasticache.Cluster',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'elasticache' },
      },
      gcp: {
        detailSlug: 'memorystore',
        terraform: 'terraform-google-modules/memorystore/redis/google',
        pulumi: 'gcp.redis.Instance',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'memorystore' },
      },
      azure: {
        detailSlug: 'redis-cache',
        terraform: 'Azure/avm-res-redis-cache/azurerm',
        pulumi: 'azure-native.cache.Redis',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'redis-cache' },
      },
      aliyun: {
        detailSlug: 'apsaradb-redis',
        terraform: 'aliyun/alicloud//modules/redis-instance',
        pulumi: 'alicloud.kvstore.Instance',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'redis' },
      },
    },
  },
  {
    key: 'queue',
    title: '队列',
    subtitle: 'Queue',
    description: '可靠的消息队列服务，解耦应用组件并支持弹性消费。',
    highlights: ['至少一次与精确一次投递模式', '死信队列与重试策略', '与事件驱动架构无缝集成'],
    products: {
      aws: 'Amazon SQS',
      gcp: 'Pub/Sub',
      azure: 'Azure Service Bus',
      aliyun: '消息服务 MNS',
    },
    iac: {
      aws: {
        detailSlug: 'sqs',
        terraform: 'terraform-aws-modules/sqs/aws',
        pulumi: 'aws.sqs.Queue',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'sqs' },
      },
      gcp: {
        detailSlug: 'pubsub',
        terraform: 'terraform-google-modules/pubsub/google',
        pulumi: 'gcp.pubsub.Topic',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'pubsub' },
      },
      azure: {
        detailSlug: 'service-bus',
        terraform: 'Azure/avm-res-servicebus-namespace/azurerm',
        pulumi: 'azure-native.servicebus.Namespace',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'service-bus' },
      },
      aliyun: {
        detailSlug: 'mns',
        terraform: 'aliyun/alicloud//modules/mns-queue',
        pulumi: 'alicloud.mns.Queue',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'mns' },
      },
    },
  },
  {
    key: 'edge_iot',
    title: '边缘计算 / IoT',
    subtitle: 'Edge & IoT',
    description: '连接海量终端设备并在边缘侧实时处理数据，助力工业与物联网场景。',
    highlights: ['设备身份与安全接入管理', '规则引擎与流式处理', '边缘部署与离线缓存'],
    products: {
      aws: 'AWS IoT Core & Greengrass',
      gcp: 'Cloud IoT Core & Edge',
      azure: 'Azure IoT Hub & IoT Edge',
      aliyun: '物联网平台 & 铂金版边缘计算',
    },
    iac: {
      aws: {
        detailSlug: 'aws-iot',
        terraform: 'terraform-aws-modules/iot/aws',
        pulumi: 'aws.iot.Thing',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'edge-iot' },
      },
      gcp: {
        detailSlug: 'gcp-iot',
        terraform: 'terraform-google-modules/iot-core/google',
        pulumi: 'gcp.iot.Registry',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'edge-iot' },
      },
      azure: {
        detailSlug: 'azure-iot',
        terraform: 'Azure/avm-res-iothub-iothub/azurerm',
        pulumi: 'azure-native.devices.IotHub',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'edge-iot' },
      },
      aliyun: {
        detailSlug: 'aliyun-iot',
        terraform: 'aliyun/alicloud//modules/iot-instance',
        pulumi: 'alicloud.iot.Instance',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'edge-iot' },
      },
    },
  },
  {
    key: 'container',
    title: '容器服务',
    subtitle: 'Container Service',
    description: '托管 Kubernetes 集群，提供自动控制面维护与节点扩缩。',
    highlights: ['一键升级与版本管理', '节点池弹性伸缩', '集成服务网格与监控'],
    products: {
      aws: 'Amazon EKS',
      gcp: 'Google Kubernetes Engine',
      azure: 'Azure Kubernetes Service',
      aliyun: '容器服务 ACK',
    },
    iac: {
      aws: {
        detailSlug: 'eks',
        terraform: 'terraform-aws-modules/eks/aws',
        pulumi: 'aws.eks.Cluster',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'eks' },
      },
      gcp: {
        detailSlug: 'gke',
        terraform: 'terraform-google-modules/kubernetes-engine/google',
        pulumi: 'gcp.container.Cluster',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'gke' },
      },
      azure: {
        detailSlug: 'aks',
        terraform: 'Azure/avm-res-containerservice-managedcluster/azurerm',
        pulumi: 'azure-native.containerservice.ManagedCluster',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'aks' },
      },
      aliyun: {
        detailSlug: 'ack',
        terraform: 'aliyun/alicloud//modules/ack-managed-kubernetes',
        pulumi: 'alicloud.cs.ManagedKubernetesCluster',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'ack' },
      },
    },
  },
  {
    key: 'data_service',
    title: '数据服务',
    subtitle: 'Data Service',
    description: '大数据与分析平台，支持批处理、交互式分析与数据湖构建。',
    highlights: ['与对象存储深度集成', '弹性集群与作业调度', '支持多种开源生态'],
    products: {
      aws: 'Amazon EMR',
      gcp: 'Dataproc',
      azure: 'Azure Synapse Analytics',
      aliyun: 'E-MapReduce',
    },
    iac: {
      aws: {
        detailSlug: 'emr',
        terraform: 'terraform-aws-modules/emr-cluster/aws',
        pulumi: 'aws.emr.Cluster',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'emr' },
      },
      gcp: {
        detailSlug: 'dataproc',
        terraform: 'terraform-google-modules/dataproc/google',
        pulumi: 'gcp.dataproc.Cluster',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'dataproc' },
      },
      azure: {
        detailSlug: 'synapse',
        terraform: 'Azure/avm-res-analytics-synapseworkspace/azurerm',
        pulumi: 'azure-native.synapse.Workspace',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'synapse' },
      },
      aliyun: {
        detailSlug: 'aliyun-emr',
        terraform: 'aliyun/alicloud//modules/emr-cluster',
        pulumi: 'alicloud.emr.Cluster',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'emr' },
      },
    },
  },
  {
    key: 'observability',
    title: '监控日志 / 事件总线',
    subtitle: 'Observability & Events',
    description: '统一采集指标、日志与事件，构建告警联动与自动化运营能力。',
    highlights: ['日志检索与指标看板', '事件路由与自动化规则', '与 APM / 安全中心整合'],
    products: {
      aws: 'Amazon CloudWatch & EventBridge',
      gcp: 'Cloud Operations & Eventarc',
      azure: 'Azure Monitor & Event Grid',
      aliyun: '云监控 CloudMonitor & EventBridge',
    },
    iac: {
      aws: {
        detailSlug: 'cloudwatch-eventbridge',
        terraform: 'terraform-aws-modules/cloudwatch/aws',
        pulumi: 'aws.cloudwatch.LogGroup',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'observability' },
      },
      gcp: {
        detailSlug: 'operations-eventarc',
        terraform: 'terraform-google-modules/logging/google',
        pulumi: 'gcp.logging.ProjectSink',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'observability' },
      },
      azure: {
        detailSlug: 'monitor-event-grid',
        terraform: 'Azure/avm-res-monitor-actiongroup/azurerm',
        pulumi: 'azure-native.insights.DiagnosticSetting',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'observability' },
      },
      aliyun: {
        detailSlug: 'cloudmonitor-eventbridge',
        terraform: 'aliyun/alicloud//modules/cms-alarm',
        pulumi: 'alicloud.cms.MetricRule',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'observability' },
      },
    },
  },
  {
    key: 'api_integration',
    title: 'API 网关 / 数据集成',
    subtitle: 'API Gateway & Integration',
    description: '统一管理 API 生命周期并打通数据管道，支撑混合云与多系统集成。',
    highlights: ['版本管理与访问控制', '节流限流与安全防护', '数据同步与 ETL 自动化'],
    products: {
      aws: 'Amazon API Gateway & AppFlow',
      gcp: 'API Gateway & Integration Connectors',
      azure: 'Azure API Management & Data Factory',
      aliyun: 'API 网关 & 数据集成 DataWorks',
    },
    iac: {
      aws: {
        detailSlug: 'api-gateway-appflow',
        terraform: 'terraform-aws-modules/apigateway-v2/aws',
        pulumi: 'aws.apigatewayv2.Api',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'api-integration' },
      },
      gcp: {
        detailSlug: 'apigateway-integration',
        terraform: 'terraform-google-modules/apigee/google',
        pulumi: 'gcp.apigateway.Api',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'api-integration' },
      },
      azure: {
        detailSlug: 'apim-data-factory',
        terraform: 'Azure/avm-res-apimanagement-service/azurerm',
        pulumi: 'azure-native.apimanagement.Api',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'api-integration' },
      },
      aliyun: {
        detailSlug: 'apigateway-dataworks',
        terraform: 'aliyun/alicloud//modules/api-gateway',
        pulumi: 'alicloud.apigateway.Api',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'api-integration' },
      },
    },
  },
  {
    key: 'iam',
    title: '身份与访问管理',
    subtitle: 'Identity & Access',
    description: '集中式身份权限管理，构建精细化访问控制与审计能力。',
    highlights: ['细粒度角色与策略', '多因子认证与单点登录', '跨账户联合与审计日志'],
    products: {
      aws: 'AWS IAM',
      gcp: 'Cloud IAM',
      azure: 'Azure Active Directory',
      aliyun: '访问控制 RAM',
    },
    iac: {
      aws: {
        detailSlug: 'iam',
        terraform: 'terraform-aws-modules/iam/aws',
        pulumi: 'aws.iam.Role',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aws', target: 'iam' },
      },
      gcp: {
        detailSlug: 'cloud-iam',
        terraform: 'terraform-google-modules/iam/google',
        pulumi: 'gcp.projects.IAMMember',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'gcp', target: 'iam' },
      },
      azure: {
        detailSlug: 'azure-ad',
        terraform: 'Azure/avm-res-authorization-roleassignment/azurerm',
        pulumi: 'azure-native.authorization.RoleAssignment',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'azure', target: 'role-assignment' },
      },
      aliyun: {
        detailSlug: 'ram',
        terraform: 'aliyun/alicloud//modules/ram-user',
        pulumi: 'alicloud.ram.Role',
        githubWorkflow: 'iac-apply.yml',
        githubInputs: { provider: 'aliyun', target: 'ram' },
      },
    },
  },
]

export const PROVIDERS: ProviderDefinition[] = [
  { key: 'aws', label: 'AWS' },
  { key: 'gcp', label: 'GCP' },
  { key: 'azure', label: 'Azure' },
  { key: 'aliyun', label: '阿里云' },
]
